[package]
name = "music-player-chromecast-addon"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["cast", "chromecast", "google"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_cast = "0.17.0"
